In [ ]:
#Titulo: Dataset Instagram
#Fecha: 27 de mayo
#Autor: Angel mtz rdz

In [2]:
#Importar librerías
import pandas as pd
import random

In [3]:
#Conjunto de datos base para Instagram influencers

datos = {
    "influencer": [
        "CancunLife",
        "TravelAna",
        "BeachVibes",
        "LuxuryParadise",
        "VisitCancun",
        "TropicalMood"
    ],

    "likes": [1200, 5000, 15000, 30000, 100000, 75000],

    "comentarios": [50, 120, 300, 500, 1200, 800],

    "fecha": [
        "2025-01-10",
        "2025-02-15",
        "2025-03-08",
        "2025-04-20",
        "2025-05-01",
        "2025-05-22"
    ],

    "tipo_post": [
        "foto",
        "reel",
        "historia",
        "video",
        "reel",
        "foto"
    ]
}

In [4]:
dfDatos = pd.DataFrame(datos)

dfDatos

       influencer   likes  comentarios       fecha tipo_post
0      CancunLife    1200           50  2025-01-10      foto
1       TravelAna    5000          120  2025-02-15      reel
2      BeachVibes   15000          300  2025-03-08  historia
3  LuxuryParadise   30000          500  2025-04-20     video
4     VisitCancun  100000         1200  2025-05-01      reel
5    TropicalMood   75000          800  2025-05-22      foto

In [5]:
cantidad = 1000000

In [6]:
dfInstagram = pd.DataFrame({

    "influencer": [
        random.choice(dfDatos["influencer"])
        for _ in range(cantidad)
    ],

    "likes": [
        random.randint(500, 500000)
        for _ in range(cantidad)
    ],

    "comentarios": [
        random.randint(10, 15000)
        for _ in range(cantidad)
    ],

    "fecha": [
        random.choice(dfDatos["fecha"])
        for _ in range(cantidad)
    ],

    "tipo_post": [
        random.choice(dfDatos["tipo_post"])
        for _ in range(cantidad)
    ]
})

In [7]:
dfInstagram.shape

(1000000, 5)

In [8]:
dfInstagram.head()

       influencer   likes  comentarios       fecha tipo_post
0     VisitCancun   66638         8902  2025-01-10      reel
1     VisitCancun   95882         8979  2025-04-20  historia
2  LuxuryParadise  479291          476  2025-05-22      reel
3      BeachVibes  101153        13213  2025-05-22  historia
4     VisitCancun  477586        14864  2025-05-01     video

In [9]:
dfInstagram.memory_usage(deep=True)

Index               132
influencer     59998658
likes           8000000
comentarios     8000000
fecha          59000000
tipo_post      53836829
dtype: int64

In [10]:
dfInstagram.memory_usage(deep=True).sum()/1024**2

np.float64(180.08767986297607)

In [11]:
#Ver tipos de datos
dfInstagram.dtypes

influencer     object
likes           int64
comentarios     int64
fecha          object
tipo_post      object
dtype: object

In [12]:
#Mostrar algunas filas
dfInstagram.head()

       influencer   likes  comentarios       fecha tipo_post
0     VisitCancun   66638         8902  2025-01-10      reel
1     VisitCancun   95882         8979  2025-04-20  historia
2  LuxuryParadise  479291          476  2025-05-22      reel
3      BeachVibes  101153        13213  2025-05-22  historia
4     VisitCancun  477586        14864  2025-05-01     video

In [13]:
#insights
dfInstagram["engagement"] = (
    dfInstagram["likes"] +
    dfInstagram["comentarios"]
)

In [14]:
dfInstagram.groupby("influencer")["engagement"].mean()

influencer
BeachVibes        257886.279044
CancunLife        257990.087849
LuxuryParadise    258317.976298
TravelAna         257311.036269
TropicalMood      257543.000631
VisitCancun       257817.022872
Name: engagement, dtype: float64

In [15]:
#Likes promedio por tipo de publicacion 
dfInstagram.groupby("tipo_post")["likes"].mean()

tipo_post
foto        250629.412645
historia    250579.552536
reel        250102.357973
video       249790.871373
Name: likes, dtype: float64